- name: Cowrie
  hosts: splunk
  
  tasks:
  
    - package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes
      become: yes

    - apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      become: yes

    - shell: lsb_release -cs
      register: release

    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ release.stdout }} stable"
        state: present
      become: yes
    
    - package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      become: yes

    - shell: uname -sm | tr ' ' -
      register: uname

    - get_url:
        url: "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-{{ uname.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: +x
      become: yes

    - service:
        name: docker
        state: started
      become: yes

    - copy:
        src: droppings/docker-compose.yml
        dest: ./docker-compose.yml

    - file:
        path: ./environment.env
        state: touch

    - blockinfile:
        path: ./environment.env
        block: |
          SPLUNK_PASSWORD = {{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}
      become: yes

    - shell: docker-compose up -d
      become: yes
